#!C:\Users\Adolfo\Documents\01 APPs_Web_Adolfo\2 Py Pysheds\venv_pysheds\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
